### ISSUE TITLE
Distributed rate limiting doesn't work (scenario 12)

### ISSUE THREAD

**Issue by rocchisanijl** [wso2/k8s-api-operator#347]
**Description:**
I follow all instruction in scenario 12 to implement distributed rate limiting and it doesn't work.

I get the following message when I call the API petstore:
curl -X GET "https://192.168.39.207:31341/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900809, "message":"Internal server error occured", "description":"POLICY ENFORCEMENT ERROR"}}

I apply the value true in parameter "enabledGlobalTMEventPublishing"
by the way there is an error in the documentation
the file "<k8s-api-operator-home>/api-operator/deploy/controller-configs/controller_conf.yaml" is not found
instead I found 2 files:
./api-operator/controller-artifacts/controller_conf.yaml
./api-operator/operatorhub-controller-configs/controller_conf.yaml
I modified and applied both

kind: ConfigMap
apiVersion: v1
metadata:
  name: apim-config
  namespace: wso2-system
  selfLink: /api/v1/namespaces/wso2-system/configmaps/apim-config
 ...
data:
  enableRealtimeMessageRetrieval: 'false'
  enableRequestValidation: 'false'
  enableResponseValidation: 'false'
  enabledGlobalTMEventPublishing: 'true'
  httpPort: '9090'
  httpsPort: '9095'
  jmsConnectionProvider: 'wso2apim.wso2:5672'
  logLevel: INFO
  throttleEndpoint: 'wso2apim.wso2:9443'
  verifyHostname: 'false'

*** important
I deleted the ratelimiting "four-req-policy.yaml" created for none distributed at the begening of scenario 12
apictl delete -f four-req-policy.yaml
and generated trace in configmap "policy-configmap"
otherwise I get no change at all in rate limiting as non distributed
***

I created the "fourreqpolicy" in APIM as explained
and after recompile the API

what I made wrong ? 

thanks in advance.

jl.rocchisani@gmail.com (société générale)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
minikube version: v1.9.2
apictl version 3.1.0

**Steps to reproduce:**

follow scenario 12

**Related Issues:**

**Comment by Uvindu96** [comment]
@rocchisanijl I was not able to reproduce this issue. This error might come because of your rate-limiting policy is missing. 
In distributed rate limiting you must create the rate-limiting policy in the API portal. check your rate-limiting policy is available there...!

**Comment by rocchisanijl** [comment]
Hi, of course I create a advanced throttle policy in API portal according explanation in sample 
**screenshot:**
![Screenshot_2020-05-04 Add API Policies](https://user-images.githubusercontent.com/27018079/80983368-c56a3a80-8e2c-11ea-8777-e6f1c1d9a410.png)


I saw in the log of the microgateway the message but what I didn't understand is the message above speaking of a sample-crd-application what is that come from

**log:**  
 name provided to retrieve auth configuration  : Petstore_Dist_Rate__v1 
2020-05-04 15:02:20,817 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Auth providers array  : oauth2 jwt 
2020-05-04 15:02:20,818 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] authHeader: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5UZG1aak00WkRrM05qWTBZemM1TW1abU9EZ3dNVEUzTVdZd05ERTVNV1JsWkRnNE56YzRaQT09In0.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllciI6IjEwUGVyTWluIiwibmFtZSI6InNhbXBsZS1jcmQtYXBwbGljYXRpb24iLCJpZCI6NCwidXVpZCI6bnVsbH0sInNjb3BlIjoiYW1fYXBwbGljYXRpb25fc2NvcGUgZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC93c28yYXBpbTozMjAwMVwvb2F1dGgyXC90b2tlbiIsInRpZXJJbmZvIjp7fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJzdWJzY3JpYmVkQVBJcyI6W10sImNvbnN1bWVyS2V5IjoieF8xal83MW11dXZCb01SRjFLZnVLdThNOVVRYSIsImV4cCI6MzczMTQ5Mjg2MSwiaWF0IjoxNTg0MDA5MjE0LCJqdGkiOiJkYTA5Mjg2Yy03OGEzLTQ4YjgtYmFiNy1hYWZiYzhiMTUxNTQifQ.MKmGDwh855NrZ2wOvXO7TwFbCtsgsOFuoZW4DBVIbJ1KQ2F6TgTgBbtzBUvrYGPslEExMemhepfvvlYv8Gd6MMo3GVH4aO8AKyc8gHmeIQ8MQtXGn7u9N00ZW3_9JWaQkU-OYEDsLHvKKHzO0t2umaskSyCS2UkAS4wIT_szZ5sm-O-ez4nKGeJmESiV-1EchFjOhLpEH4p9wIj3MlKnZrIcJByRKK9ZGaHBqxwwYuJtMCDNa2wFAPMOh-45eabIUdo1KUO3gZLVcME93aza1t1jzL9mFsx0LGaXIxB7klrDuBCAdG9Yi3O7-3WUF74QaS2tmCxW36JhhOJ5DdacfQ 
2020-05-04 15:02:20,819 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Provider Id for authentication handler : jwt 
2020-05-04 15:02:20,820 DEBUG [wso2/gateway/src/gateway/utils] - [AuthnFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Request will authenticated via jwt handler 
2020-05-04 15:02:20,821 DEBUG [ballerina/jwt] - Authenticate user :admin@carbon.super from cache 
2020-05-04 15:02:20,823 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [86a36ac6-73a0-49a1-983b-10c5c265afc5] jwt found from the jwt cache 
2020-05-04 15:02:20,823 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [86a36ac6-73a0-49a1-983b-10c5c265afc5] jti claim found in the jwt 
2020-05-04 15:02:20,824 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Checking for the JTI in the gateway invalid revoked token map. 
2020-05-04 15:02:20,825 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [86a36ac6-73a0-49a1-983b-10c5c265afc5] JTI token not found in the invalid token map. 
2020-05-04 15:02:20,826 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [86a36ac6-73a0-49a1-983b-10c5c265afc5] subscribedAPIs claim found in the jwt. 
2020-05-04 15:02:20,827 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [86a36ac6-73a0-49a1-983b-10c5c265afc5] **Set username : admin@carbon.super, keytype : PRODUCTION, consumer key : x_1j_71muuvBoMRF1KfuKu8M9UQa, application ID : 4, application name : sample-crd-application, application tier : 10PerMin, application owner : admin, application tier : Default, apiTier : Unlimited, apiPublisher : __unknown__, subscriberTenantDomain : __unknown__** 
2020-05-04 15:02:20,828 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Subscriptions validation passed. 
2020-05-04 15:02:20,829 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [86a36ac6-73a0-49a1-983b-10c5c265afc5] jwt found from the jwt cache 
2020-05-04 15:02:20,830 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Processing request via Authorization filter. 
2020-05-04 15:02:20,831 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Auth scheme was resolved as : jwt 
2020-05-04 15:02:20,832 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Returned with value: true 
2020-05-04 15:02:20,833 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Removed header : Authorization from the request 
2020-05-04 15:02:20,833 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Processing the request in ThrottleFilter 
2020-05-04 15:02:20,834 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] Context contains Authentication Context 
2020-05-04 15:02:20,835 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] **[86a36ac6-73a0-49a1-983b-10c5c265afc5] Checking api level throttle policy 'fourreqpolicy' exist. 
2020-05-04 15:02:20,835 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [86a36ac6-73a0-49a1-983b-10c5c265afc5] API level throttle policy 'fourreqpolicy' does not exist.**

**Comment by rocchisanijl** [comment]
I understand the application name sample-crd-application came from the TOKEN given in the sample
as a test i publish the API in the portal through APICTL, create another "fourreqpolicy" but in category application, make it attached to the default app "default-apictl-app", retrieve an access TOKEN but nothing change same error message except in the log where the right app and information of its attachment to fourreqpolicy is mentionned.
It is logical I would be surprised it works. the policy is attached to the API through the swagger file.
perhaps if I removed the "x-wso2-throttling-tier: fourreqpolicy" in the swagger then the policy attached to the TOKEN would apply.
I think It came from the yellow message I got in the policy edit screen:
"Warning! Publishing Query Params , Header Data and JWT Token isn't configured. If a policy is configured with any of these conditions, it won't be applied. "
As it is not explained in the sample I was not able to correctly setting it.

**Comment by rocchisanijl** [comment]
in addition the log to complete my previous message 
2020-05-04 15:55:19,021 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [9b565147-e03a-439f-8365-a9f9499b12e0] **Set username : admin@carbon.super, keytype : PRODUCTION, consumer key : 5qqjgdjfJOgMRrzm4J5DSwMNJHka, application ID : 2, application name : default-apictl-app, application tier : fourreqpolicy, application owner : admin, application tier : Unlimited, apiTier : Unlimited, apiPublisher : admin, subscriberTenantDomain : carbon.super** 
2020-05-04 15:55:19,022 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [9b565147-e03a-439f-8365-a9f9499b12e0] Subscriptions validation passed. 
2020-05-04 15:55:19,023 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [9b565147-e03a-439f-8365-a9f9499b12e0] jwt found from the jwt cache 
2020-05-04 15:55:19,023 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Processing request via Authorization filter. 
2020-05-04 15:55:19,024 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Auth scheme was resolved as : jwt 
2020-05-04 15:55:19,024 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Returned with value: true 
2020-05-04 15:55:19,025 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Removed header : Authorization from the request 
2020-05-04 15:55:19,025 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Processing the request in ThrottleFilter 
2020-05-04 15:55:19,026 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Context contains Authentication Context 
2020-05-04 15:55:19,026 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] Checking api level throttle policy 'fourreqpolicy' exist. 
2020-05-04 15:55:19,027 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [9b565147-e03a-439f-8365-a9f9499b12e0] API level throttle policy 'fourreqpolicy' does not exist. 
2020-05-04 15:55:19,546 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [-] Skip all filter annotation set in the service. Skip the filter

**Comment by rocchisanijl** [comment]
I made another test:
removed policy in the swagger:
...
x-wso2-basePath: /petstoredistrate/{version}
# x-wso2-throttling-tier: fourreqpolicy
paths:
...
subscribed with "default-apictl-app" with Subscription Throttling Policies "fourreqpolicy"
get a new access TOKEN

but I got the same message !!!
I missed something apparently.

log:
Auth providers array  : oauth2 jwt 
2020-05-04 16:54:53,475 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] authHeader: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5UZG1aak00WkRrM05qWTBZemM1TW1abU9EZ3dNVEUzTVdZd05ERTVNV1JsWkRnNE56YzRaQT09In0.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsInRpZXIiOiJmb3VycmVxcG9saWN5IiwibmFtZSI6ImRlZmF1bHQtYXBpY3RsLWFwcCIsImlkIjoyLCJ1dWlkIjpudWxsfSwic2NvcGUiOiJhbV9hcHBsaWNhdGlvbl9zY29wZSBkZWZhdWx0IiwiaXNzIjoiaHR0cHM6XC9cL3dzbzJhcGltOjMyMDAxXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiZm91cnJlcXBvbGljeSI6eyJ0aWVyUXVvdGFUeXBlIjoicmVxdWVzdENvdW50Iiwic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6LTEsInNwaWtlQXJyZXN0VW5pdCI6Ik5BIn19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInN1YnNjcmliZWRBUElzIjpbeyJzdWJzY3JpYmVyVGVuYW50RG9tYWluIjoiY2FyYm9uLnN1cGVyIiwibmFtZSI6IlBldHN0b3JlLURpc3QtUmF0ZSIsImNvbnRleHQiOiJcL3BldHN0b3JlZGlzdHJhdGVcL3YxIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoidjEiLCJzdWJzY3JpcHRpb25UaWVyIjoiZm91cnJlcXBvbGljeSJ9XSwiY29uc3VtZXJLZXkiOiI1cXFqZ2RqZkpPZ01ScnptNEo1RFN3TU5KSGthIiwiZXhwIjoxNTg4NjE0NzUxLCJpYXQiOjE1ODg2MTExNTEsImp0aSI6Ijk5ZWE1NmI2LTYyMGYtNGQwNy1iNWVkLWNlMDAyNDI5ZTYxMSJ9.wkfe9AreQdqlF0_jFA3gcZpQ8-jit8I1F9QKNIM1g8hl3RMQP-OKBhn6tNfCNqICsZY_KU1e3HSj-cN8avwXutmbQpol1NzvYpV5ptu6rpX7eks4ZoJ6psCaHlXnrXMt2vCJzbS6G5W4GmuQVg5yiPQm8slj5vKl4U28xZzM_ApHKCwFf0oIfSMSGkmzJoQWq2QtLcHzZopN01ozDvrOIWK4kchYAtI5ZLUCuqAFNnxF1evYkmBFsGu4cuDYzBhmKuVluhwK1-OnBb9R8hqupFtpizOsC2NRA1m2P2PbX-8B3-1Q5iY-dcEKfkPt6APfxiwL2jabxtYa9jv5t1SEqQ 
2020-05-04 16:54:53,475 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Provider Id for authentication handler : jwt 
2020-05-04 16:54:53,476 DEBUG [wso2/gateway/src/gateway/utils] - [AuthnFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Request will authenticated via jwt handler 
2020-05-04 16:54:53,476 DEBUG [ballerina/jwt] - Authenticate user :admin@carbon.super from cache 
2020-05-04 16:54:53,477 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [23ebdb8c-7e61-414d-813a-d1f458c006cc] jwt found from the jwt cache 
2020-05-04 16:54:53,477 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [23ebdb8c-7e61-414d-813a-d1f458c006cc] jti claim found in the jwt 
2020-05-04 16:54:53,477 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Checking for the JTI in the gateway invalid revoked token map. 
2020-05-04 16:54:53,477 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [23ebdb8c-7e61-414d-813a-d1f458c006cc] JTI token not found in the invalid token map. 
2020-05-04 16:54:53,478 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [23ebdb8c-7e61-414d-813a-d1f458c006cc] subscribedAPIs claim found in the jwt. 
2020-05-04 16:54:53,478 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Found a matching allowed api with name:Petstore-Dist-Rate version:v1 
2020-05-04 16:54:53,478 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [23ebdb8c-**7e61-414d-813a-d1f458c006cc] Set username : admin@carbon.super, keytype : PRODUCTION, consumer key : 5qqjgdjfJOgMRrzm4J5DSwMNJHka, application ID : 2, application name : default-apictl-app, application tier : fourreqpolicy, application owner : admin, application tier : fourreqpolicy, apiTier : Unlimited, apiPublisher : admin, subscriberTenantDomain : carbon.super 
2020-05-04 16:54:53,478 DEBUG [wso2/gateway/src/gateway/utils] - [JWTAuthProvider] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Subscriptions validation passed.** 
2020-05-04 16:54:53,479 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [23ebdb8c-7e61-414d-813a-d1f458c006cc] jwt found from the jwt cache 
2020-05-04 16:54:53,479 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Processing request via Authorization filter. 
2020-05-04 16:54:53,479 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Auth scheme was resolved as : jwt 
2020-05-04 16:54:53,479 DEBUG [wso2/gateway/src/gateway/utils] - [AuthzFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Returned with value: true 
2020-05-04 16:54:53,480 DEBUG [wso2/gateway/src/gateway/utils] - [PreAuthnFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Removed header : Authorization from the request 
2020-05-04 16:54:53,480 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Processing the request in ThrottleFilter 
2020-05-04 16:54:53,480 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Context contains Authentication Context 
2020-05-04 16:54:53,481 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [23ebdb8c-7e61-414d-813a-d1f458c006cc] Checking api level throttle policy 'fourreqpolicy' exist. 
2020-05-04 16:54:53,481 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [23ebdb8c-**7e61-414d-813a-d1f458c006cc] API level throttle policy 'fourreqpolicy' does not exist.**

**Comment by pubudu538** [comment]
I think I know what is really happening here. Although you change your Swagger definition, it does not update the API microgateway. When you add an API, the API Operator checks whether the docker image of the API exists in the docker hub or given registry. If it finds a docker image, it doesn't run the Kaniko job. 

To overcome this you can add the API as follows.

apictl add api -n <API_NAME> --from-file=<LOCATION_TO_THE_OPEN_API_DEFINITION> --override

So with override flag, that docker image is overridden with the changes. If you want to update an API that is already running, you can run apictl update api command

**Comment by rocchisanijl** [comment]
Hi guys,
I'm not stupid.
I generate API with --override flag as example 12 is explaining.
is anyone could take my case seriously please?

**Comment by rocchisanijl** [comment]
I made another test for distributed rating.
in the config map i have the flag  **enabledGlobalTMEventPublishing: 'true'**

data:
  enableRealtimeMessageRetrieval: 'false'
  enableRequestValidation: 'false'
  enableResponseValidation: 'false'
  **enabledGlobalTMEventPublishing: 'true'**
  httpPort: '9090'
  httpsPort: '9095'
  jmsConnectionProvider: 'wso2apim.wso2:5672'
  logLevel: TRACE
  throttleEndpoint: 'wso2apim.wso2:9443'
  verifyHostname: 'false'



I use the TOKEN provided in scenario 12.

authHeader: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5UZG1aak00WkRrM05qWTBZemM1TW1abU9EZ3dNVEUzTVdZd05ERTVNV1JsWkRnNE56YzRaQT09In0.eyJhdWQiOiJodHRwOlwvXC9vcmcud3NvMi5hcGltZ3RcL2dhdGV3YXkiLCJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllciI6IjEwUGVyTWluIiwibmFtZSI6InNhbXBsZS1jcmQtYXBwbGljYXRpb24iLCJpZCI6NCwidXVpZCI6bnVsbH0sInNjb3BlIjoiYW1fYXBwbGljYXRpb25fc2NvcGUgZGVmYXVsdCIsImlzcyI6Imh0dHBzOlwvXC93c28yYXBpbTozMjAwMVwvb2F1dGgyXC90b2tlbiIsInRpZXJJbmZvIjp7fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJzdWJzY3JpYmVkQVBJcyI6W10sImNvbnN1bWVyS2V5IjoieF8xal83MW11dXZCb01SRjFLZnVLdThNOVVRYSIsImV4cCI6MzczMTQ5Mjg2MSwiaWF0IjoxNTg0MDA5MjE0LCJqdGkiOiJkYTA5Mjg2Yy03OGEzLTQ4YjgtYmFiNy1hYWZiYzhiMTUxNTQifQ.MKmGDwh855NrZ2wOvXO7TwFbCtsgsOFuoZW4DBVIbJ1KQ2F6TgTgBbtzBUvrYGPslEExMemhepfvvlYv8Gd6MMo3GVH4aO8AKyc8gHmeIQ8MQtXGn7u9N00ZW3_9JWaQkU-OYEDsLHvKKHzO0t2umaskSyCS2UkAS4wIT_szZ5sm-O-ez4nKGeJmESiV-1EchFjOhLpEH4p9wIj3MlKnZrIcJByRKK9ZGaHBqxwwYuJtMCDNa2wFAPMOh-45eabIUdo1KUO3gZLVcME93aza1t1jzL9mFsx0LGaXIxB7klrDuBCAdG9Yi3O7-3WUF74QaS2tmCxW36JhhOJ5DdacfQ 

this token was apparently provided with the **application tiers "10PerMin"** as the log of microgateway is proving:

2020-05-09T16:22:15.617779635Z  2020-05-09 16:22:15,617 DEBUG [wso2/gateway/src/gateway/utils] - [JWTUtil] [c647121e-37cd-428b-bd03-6d695ff2c15f] Set username : admin@carbon.super, keytype : PRODUCTION, consumer key : x_1j_71muuvBoMRF1KfuKu8M9UQa, application ID : 4, application name : sample-crd-application, **application tier : 10PerMin**, application owner : admin, application tier : Default, apiTier : Unlimited, apiPublisher : __unknown__, subscriberTenantDomain : __unknown__ 

So I made a test, starting at time **samedi 9 mai 2020, 18:22:11 (UTC+0200)**
I execute request and repeat it quickly 
curl -X GET "https://192.168.39.207:32644/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k

I got 17 answers before throttled out message.
/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"**code":900803, "message":"Message throttled out", "description":"You have exceeded your quota"}}**
I made the test in the same minute as date is proving
samedi 9 mai 2020, **18:22**:33 (UTC+0200)


I was expecting 10 and not 17 
It seems the distributed throttling is not working well. 

I checked the logs (with trace level) I found 19 messages **"throttled out: false"** before message **Application level throttled out. Sending throttled out response.** 

on pod 1
2020-05-09T16:22:16.968331191Z  2020-05-09 16:22:16,968 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [9790d6ea-62e6-47ff-b0af-b60860542d1c] Application level **throttled out: false** 
... # count 1
2020-05-09T16:22:17.850499594Z  2020-05-09 16:22:17,850 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [9b5d33d7-5f6e-4be2-b13b-4536a205df5c] Application level throttled out: false 
... # count 2
2020-05-09T16:22:19.43971358Z  2020-05-09 16:22:19,439 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [5a1a6099-444c-4e1e-8fd2-035b5a324917] Application level throttled out: false 
... # count 3
2020-05-09T16:22:24.380279858Z  2020-05-09 16:22:24,380 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [36744ae9-c58d-45c7-ada7-67cd737c9bae] Application level throttled out: false
... # count 4
2020-05-09T16:22:24.973619694Z  2020-05-09 16:22:24,973 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [51c49da6-7a8c-4ea2-915c-b9eedd10b2ce] Application level throttled out: false
... # count 5
2020-05-09T16:22:25.600545523Z  2020-05-09 16:22:25,600 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [c89e9471-4e02-4797-9f6f-58fbe9b26d52] Application level throttled out: false 
... # count 6
2020-05-09T16:22:26.797864124Z  2020-05-09 16:22:26,797 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [f3a35280-6d5d-4dc8-b9c4-e92bb6fb5fe0] Application level throttled out: false 
... # count 7

Pod 2

2020-05-09T16:22:15.621193796Z  2020-05-09 16:22:15,621 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [c647121e-37cd-428b-bd03-6d695ff2c15f] Resource level throttled out: false 
... # count 8
2020-05-09T16:22:15.622855025Z  2020-05-09 16:22:15,622 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [c647121e-37cd-428b-bd03-6d695ff2c15f] Application level throttled out: false 
... # count 9
2020-05-09T16:22:18.685455482Z  2020-05-09 16:22:18,685 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [26575f86-7479-4c18-811f-9b0a0af02a84] Application level throttled out: false 
... # count 10
2020-05-09T16:22:20.095075744Z  2020-05-09 16:22:20,094 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [640cf814-c231-4ee7-b4d5-31212904a152] Application level throttled out: false 
... # count 11
2020-05-09T16:22:20.756601349Z  2020-05-09 16:22:20,756 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [ec0ec4c5-ea4d-4b01-b8fe-7716965cf2d3] Application level throttled out: false 
... # count 12
2020-05-09T16:22:21.387752391Z  2020-05-09 16:22:21,387 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [a318764b-ed5c-4384-98f3-2c75a31478e3] Application level throttled out: false
... # count 13
2020-05-09T16:22:22.024757273Z  2020-05-09 16:22:22,024 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [b3f529fe-d9d8-4f0d-a5fe-8b51b767004d] Application level throttled out: false
... # count 14
2020-05-09T16:22:22.567314718Z  2020-05-09 16:22:22,567 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [ced5866d-071e-402a-9a3e-a973e23f43f8] Application level throttled out: false
... # count 15
2020-05-09T16:22:23.174572221Z  2020-05-09 16:22:23,174 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [8d18ec8a-82b8-47a8-8772-2bdacb6b247b] Application level throttled out: false 
... # count 16
2020-05-09T16:22:23.773320113Z  2020-05-09 16:22:23,773 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [d5594791-c61f-4742-95dc-c6a47da801ac] Application level throttled out: false 
... # count 17
020-05-09T16:22:26.223358228Z  2020-05-09 16:22:26,222 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [44cce5dc-9228-4cbc-93cb-fa3ac9894f45] Application level throttled out: false 
... # count 18
2020-05-09T16:22:27.412519393Z  2020-05-09 16:22:27,412 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [26d0f51a-dbce-46f1-8c1e-cb165792db1e] Checking application level throttling-out. 
... # count 19
[1e283512-6cf2-43a6-b168-c61c339d4b93] Checking application level throttle policy '10PerMin' exist. 
2020-05-09T16:22:28.014294841Z  2020-05-09 16:22:28,013 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [1e283512-6cf2-43a6-b168-c61c339d4b93] Checking application level throttling-out. 
2020-05-09T16:22:28.014300844Z  2020-05-09 16:22:28,013 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [1e283512-6cf2-43a6-b168-c61c339d4b93] Application level throttle key : 4:admin@carbon.super 
2020-05-09T16:22:28.014306234Z  2020-05-09 16:22:28,014 DEBUG [wso2/gateway/src/gateway/utils] - [ThrottleFilter] [1e283512-6cf2-43a6-b168-c61c339d4b93] **Application level throttled out. Sending throttled out response.** 

What is going wrong ???

**Comment by rocchisanijl** [comment]
I continue tests 
in the config map i still have the flag enabledGlobalTMEventPublishing: 'true'
I created an advanced "fourreqpolicy"
and 
I reactivated the "x-wso2-throttling-tier: fourreqpolicy" in the swagger.

recompile the mgw 

but got message {"fault":{"code":900809, "message":"Internal server error occured", "description":"POLICY ENFORCEMENT ERROR"}

I tried to create manually data in the configmap "policy-configmap"

recompile the mgw 

but got same message {"fault":{"code":900809, "message":"Internal server error occured", "description":"POLICY ENFORCEMENT ERROR"}

then I created the policy with Yaml
apictl apply -f four-req-poliy.yaml
ratelimiting.wso2.com/fourreqpolicy created

recompile the mgw 

Then i got this:

```
@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 9 mai 2020, **21:30**:04 (UTC+0200)

```
**#Req number 1**
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>
```

**#Req number 2**
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>
```

**#Req number 3**
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>
```

**#Req number 4**
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>

```
**#Req number 5** it is still working
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>
```

**#Req number 6** throttled at last
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 9 mai 2020, 21:30:27 (UTC+0200)
```

but 
**#Req number 7 (in fact 6 not throtlled) ** still work and same minute
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>

```
**#Req number 8** (in fact 7 not throtlled) still work
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}

```
**#Req number 9 (in fact 8 not throtlled) ** still work
```
jlr9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k.39
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>
```

**#Req number 10 (in fact 9 not throtlled) ** still work I was expected it was throlled
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>

```
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 9 mai 2020, **21:30**:46 (UTC+0200)
```

**#Req number 10** throttled at last
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}

```
```
**#Req number 11** throttled seems we reach the limit
jlr9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k.39
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}
```

**#Req number 12** throttled
```
jlr9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k.39
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}

```
**#Req number 12** throttled 
```
jlr9.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k.39
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}

```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 9 mai 2020, **21:30**:58 (UTC+0200)

**#Req number 12** it works but normal it is another minute
```
`jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:30928/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><apiResponse><message>Pet not found</message><type>error</type></apiResponse>

```
```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 9 mai 2020, **21:31**:05 (UTC+0200)
```
It seems distributed is not working 
so go back to my first message
do you really retest this in 3.1 ?

**Comment by dinusha92** [comment]
Hi @rocchisanijl ,

Thanks for bringing this to our attention.

I tested this today and I got it to work. However, I had to do some modifications.

Open the following file in the API Operator distribution.
```
k8s-api-operator-1.1.0/api-operator/controller-artifacts/mgw_conf_mustache.yaml
```

Then you have to comment only the following configuration section.
```
  # [throttlingConfig.nodeLocal]
      #   # Core number of threads in the thread pool.
      #   processThreadPoolCoreSize = 200
      #   # Maximum number of threads in the thread pool.
      #   processThreadPoolMaximumSize = 1000
      #   # Keep alive time of the threads in seconds
      #   processThreadPoolKeepAliveTime = 200
      #   # Throttle data cleanup task frequency in seconds.
      #   cleanUpFrequency = 3600
```

Then reapply that configuration file.
```
kubectl apply -f k8s-api-operator-1.1.0/api-operator/controller-artifacts/mgw_conf_mustache.yaml
```

Then delete the available API with the name "petstore-dist-rate"

Create the API again.
```
apictl add api -n petstore-dist-rate --from-file=swagger.yaml --replicas=2 --override=true
```

Then I worked as expected.

Let us know if you need more clarifications.

**Comment by rocchisanijl** [comment]
Hi, Sorry but it is still not working.
did everything as you but ...
I got still erratic results  

```
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>string</name></category><id>55</id><name>SRC_TIME_SIZE</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>string</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:13 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>string</name></category><id>55</id><name>SRC_TIME_SIZE</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>string</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:19 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>string</name></category><id>55</id><name>SRC_TIME_SIZE</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>string</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:24 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>string</name></category><id>55</id><name>SRC_TIME_SIZE</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>string</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:28 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:34 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>string</name></category><id>55</id><name>SRC_TIME_SIZE</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>string</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:40 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:45 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:50 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>string</name></category><id>55</id><name>SRC_TIME_SIZE</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>string</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:21:57 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.207:31246/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
lundi 18 mai 2020, 18:22:03 (UTC+0200)
```

**Comment by dinusha92** [comment]
Hi @rocchisanijl ,

We will internally test this again and try to replicate the behaviour that you are observing above and we'll update you at our earliest.

**Comment by renuka-fernando** [comment]
Hi @rocchisanijl 

We could find the issue and it is related to the micro-gateway toolkit. We pushed the updated toolkit docker image.
Can you please change your `controller-artifacts/controller_conf.yaml` with following and try. We tested this and worked fine :)

```yaml
data:
  #mgw toolkit image to initialize/setup the micro gw project
  mgwToolkitImg: wso2am/wso2micro-gw-toolkit:3.1.0-1589188374808
```

**Comment by rocchisanijl** [comment]
hi I tested it again recreating from scratch and applying your patch but it seems it is still not working

```
lr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 30 mai 2020, 17:26:00 (UTC+0200)
jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ curl -X GET "https://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "accept: application/xml" -H "Authorization:Bearer $TOKEN" -k
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Pet><category><id>55</id><name>123</name></category><id>55</id><name>123</name><photoUrls><photoUrl>string</photoUrl></photoUrls><status>available</status><tags><tag><id>55</id><name>123</name></tag></tags></Pet>jlr@jlr-MACH-WX9:~/programs/wso2/k8s-accept: application/xml" -H "Authorization:Bearer $TOKEN" -k://192.168.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operatccept: application/xml" -H "Authorization:Bearer $TOKEN" -k8.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operatccept: application/xml" -H "Authorization:Bearer $TOKEN" -k8.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operatccept: application/xml" -H "Authorization:Bearer $TOKEN" -k8.39.94:30097/petstoredistrate/v1/pet/55" -H "ac
{"fault":{"code":900800, "message":"Message throttled out", "description":"You have exceeded your quota"}}jlr@jlr-MACH-WX9:~/programs/wso2/k8s-api-operator-1.1.0/scenarios/scenario-12$ date
samedi 30 mai 2020, 17:26:19 (UTC+0200))
```
